const languages = [
    "English",
    "Hausa",
    "Yoruba",
    "Igbo",
    "Fulfulde (Fula)",
    "Igala",
    "Kanuri",
    "Tiv",
    "Ibibio",
    "Edo",
    "Nupe",
    "Ijaw",
    "Kadara (Kanuri)",
    "Berom",
    "Igede",
    "Itsekiri",
    "Tiv",
    "Ijaw",
    "Efik",
    "Urhobo",
    "Kaningkon (Kambari)",
    "Jukun",
    "Kanufi",
    "Margi",
    "Bassa",
    "Anufo",
    "Ngizim",
    "Ogoni",
    "Birom",
    "Bachama",
    "Ebira",
    "Izon (Ijaw)",
    "Idoma",
    "Gwari",
    "Nkwen (Bali)",
    "Abua",
    "Agatu",
    "Atyap",
    "Kamuku",
    "Kamwe",
    "Lamang",
    "Margi",
    "Mbula-Bwazza",
    "Mupun",
    "Ndoro",
    "Nyankpa",
    "Nyeng",
    "Ogbia",
    "Oron",
    "Owan",
    "Sobo",
    "Tula",
  ];
  
  export default languages;